### ISSUE TITLE
Log table might violate Constraint-Typing-Preferred

### ISSUE THREAD

**Issue by mongj** [AY2425S1-CS2103T-W13-2/tp#130]
**Describe the bug**
There is currently no way to navigate the list of logs other than using a mouse to scroll, this might be considered a violation of the Constraint-Typing-Preferred constraint.

We can table this for discussion

**Comment by SuhailLoya** [comment]
As discussed, we will implement a shift focus cycle on key press. So CLI users can shift focus to log list and scroll using arrows keys
