### ISSUE TITLE
Clarify Meaning of Colours for Syntax Highlighting

### ISSUE THREAD

**Issue by SuhailLoya** [AY2425S1-CS2103T-W13-2/tp#152]
**Describe the bug**
Currently, syntax highlighting shows "black" if the command box contains a valid full command that can be executed like

<img width="179" alt="Screenshot 2024-11-01 at 7 38 21 AM" src="https://github.com/user-attachments/assets/9b3dea3a-b6df-4c25-9c47-13628a84fa85">

Or if the word in the command box is a valid commandword (may not be executable yet)

<img width="239" alt="Screenshot 2024-11-01 at 7 38 01 AM" src="https://github.com/user-attachments/assets/4b3e946d-c83f-43b5-b6fa-aba44d929198">

This overloads the black color to mean 2 things, either the command is executable or the commandword is correct which might lead to some confusion. 

**Solution**
Specify this more clearly in user guide OR use a different color for one of the above scenarios

**Comment by mongj** [comment]
closing this issue as it as been resolved in #177
