### ISSUE TITLE
[PE-D][Tester C] setappointment feature flaw

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#192]
![image.png](https://raw.githubusercontent.com/btbrandon/ped/main/files/52779e0f-5eac-4022-9c78-db1fbda1e748.png)

command: 
setappointment 1 d/2024-11-07

current date: 2024-11-08

As an end-user, it might be undesired to set the next appointment as a date that has already passed.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: btbrandon/ped#6

**Comment by mongj** [comment]
@SuhailLoya do you mind taking a look at this

**Comment by SuhailLoya** [comment]
this was allowed to not enforce Overzealous input validation. Users might forget to add a appt date before the date has passed and this will allow them to at least keep a record. But perhaps a warning can be displayed here. Overall, still not in scope since not important enough to be done in v1.6
