### ISSUE TITLE
[PE-D][Tester A] Incorrect example provided for delete command in User guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#193]
## Example provided in user guide for delete command does not work as expected

Steps to reproduce
1) add n/Betsy p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
2) find Betsy 

Expected: Betsy beneficiary to be displayed and able to run the delete 1 command
Actual: Invalid command usage displayed for find command

![Screenshot 2024-11-08 at 4.34.23 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/3dd632a7-a6cf-4d81-9fe8-ef761dbab998.png)

![Screenshot 2024-11-08 at 4.37.21 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/032a1230-bdcc-4bd4-b79c-2e571134119d.png)*

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CJianzhi/ped#2

**Comment by mongj** [comment]
@AppleJem do you mind taking a look at this

**Comment by AppleJem** [comment]
Misleading error message
