### ISSUE TITLE
[PE-D][Tester C] Duplicate phone number Feature Flaw

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#195]
![image.png](https://raw.githubusercontent.com/btbrandon/ped/main/files/456f354f-6f96-4db3-a3d9-6e6d36475691.png)

command:
add n/Bob p/91031282 e/bob@gmail.com a/551122

able to add a new person with an already existing phone number might not be ideal given that phone numbers are unique.

As an end-user, this might not be very ideal.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: btbrandon/ped#7

**Comment by mongj** [comment]
@SuhailLoya @AppleJem @celeschai should we address this?

We can also argue that not all clients have mobile phones, so the contact may belong to their caregivers etc.

**Comment by AppleJem** [comment]
I agree, let's just update the UG regarding this

**Comment by SuhailLoya** [comment]
Honestly this is okay. We can safely reject the bug since 2 beneficiaries might provide the same phone number. It may be their house phone number or might be a common relative's phone number if the beneficiaries don't have their own phones
