### ISSUE TITLE
[PE-D][Tester C] UG lack of examples

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#205]
![image.png](https://raw.githubusercontent.com/btbrandon/ped/main/files/ef61a06c-7be5-4366-8c3d-91a5efd1aaba.png)

Lack of examples for addlog and deletelog

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: btbrandon/ped#10

**Comment by mongj** [comment]
@celeschai do you mind taking a look at this?

**Comment by AppleJem** [comment]
I feel like we can just limit the length of tags

**Comment by celeschai** [comment]
> I feel like we can just limit the length of tags

Why tags?
