### ISSUE TITLE
[PE-D][Tester C] Inconsistent Language in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#210]
![image.png](https://raw.githubusercontent.com/btbrandon/ped/main/files/0b92275a-b7f4-4302-9af6-702a05f258d9.png)

Inconsistent language usage, makes UG slightly messy

e.g., View the detail vs Edits an existing..., Tags a client... etc

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: btbrandon/ped#13

**Comment by AppleJem** [comment]
Actually makes a bit of sense to unify the language after we're all done with individual updates

**Comment by mongj** [comment]
closing this as ug has been updated
