### ISSUE TITLE
[PE-D][Tester D] Autocomplete confusing for delete and deletelog

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#211]
![image.png](https://raw.githubusercontent.com/leroytan/ped/main/files/703f55b8-219e-4ded-8429-b374e886473a.png)

Reproduce: type in del, then press tab, the autocomplete will give me `delete `, notice the space behind. Due to this space, pressing tab again will fail to give me deletelog.

I might be wrong, but I would assume the expected behaviour is that the user does not need to remove the extra space and press tab again to get `deletelog`. This is particulary important for fast typist after all.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: leroytan/ped#7

**Comment by mongj** [comment]
@SuhailLoya i think this makes sense actually. not sure if we are allowed to do it during feature freeze though

I think it would make sense if the behavior of autocomplete is:
- if the completed command is a prefix of one or more other commands, then we do not add a space behind
- else add a space behind
