### ISSUE TITLE
[PE-D][Tester C] User Stories too brief

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#216]
![image.png](https://raw.githubusercontent.com/btbrandon/ped/main/files/a861d7a6-c752-4eb0-bdb9-6214e2a4bf2d.png)

Features cover a lot more ground than user stories.

Might want to consider adding more user stories to better fit the features.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: btbrandon/ped#15

**Comment by AppleJem** [comment]
Ah yes we should all update this, will do the part on searching and filtering for contacts

**Comment by mongj** [comment]
done
