### ISSUE TITLE
[PE-D][Tester D] Command Summary Find command is erroneous

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#217]
![image.png](https://raw.githubusercontent.com/leroytan/ped/main/files/b4834f7a-f3cd-41ca-afb3-0b0a1686824a.png)

The find command in the command summary is wrong, does not include the tags necessary. (e.g. find n/KEYWORD [MORE_KEYWORDS] [a/KEYWORD] [MORE_KEYWORDS]

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: leroytan/ped#9

**Comment by mongj** [comment]
@AppleJem do you mind taking a look at this?

**Comment by AppleJem** [comment]
Got it
