### ISSUE TITLE
[PE-D][Tester E] Application non responsive after adding too many logs

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#222]
Steps to reproduce
1. List user
2. use addlog command continuously with string length of 10K for about 23-24 times

<i><video controls><source src="https://raw.githubusercontent.com/tohhengxing/ped/main/files/c0312650-634b-4196-bd2e-304e0d29bef8.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/tohhengxing/ped/main/files/c0312650-634b-4196-bd2e-304e0d29bef8.mov</i>

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tohhengxing/ped#1

**Comment by mongj** [comment]
@SuhailLoya @AppleJem @celeschai I think we can't do much about this, should we enforce max length for some of the fields and/or add a clause under non-functional requirement that the application is only expected to handle input lengths of up to x

**Comment by AppleJem** [comment]
230k words is ... insane.

**Comment by celeschai** [comment]
does it help to put it in NFR?

**Comment by celeschai** [comment]
closed with previous PR
