### ISSUE TITLE
[PE-D][Tester B] Future date checking feature doesn't support different timezones

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#226]
> Command: addlog 1 r/First meetup. d/2024-11-08 17:40

When I'm in a different timezone that is faster than GMT +8. The date checking function still blocks me from adding the log.

![image.png](https://raw.githubusercontent.com/QinHaichen12/ped/main/files/a10fc7e3-cbe4-437e-9568-35efa792891b.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: QinHaichen12/ped#10

**Comment by mongj** [comment]
@AppleJem @SuhailLoya @celeschai oh no

**Comment by AppleJem** [comment]
Bruh what the...

**Comment by SuhailLoya** [comment]
Not important enough to be in v1.6 to support different time zones
