### ISSUE TITLE
[PE-D][Tester D] Developer Guide (stuff not removed from AB3)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#230]
![image.png](https://raw.githubusercontent.com/leroytan/ped/main/files/727826b1-e718-4b29-b63e-85e108be839a.png)

![image.png](https://raw.githubusercontent.com/leroytan/ped/main/files/fd4a262d-eb44-4cf0-8cf5-8993e1971466.png)

Consider removing the undo/redo proposed feature, as well as the data archiving, because it is not used in your application.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: leroytan/ped#13

**Comment by mongj** [comment]
@SuhailLoya @AppleJem @celeschai should we just remove this section? And add in the implementation details for some of the more complex features like autocomplete, syntax highlighting and shift+tab

**Comment by celeschai** [comment]
I think @SuhailLoya is more familiar with the parts @mongj mentioned.

**Comment by mongj** [comment]
done via #275
