### ISSUE TITLE
[PE-D][Tester A] Two clients with all fields different but same name is taken as duplicate

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#234]
steps to reproduce
1) add n/John tan p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
2) add n/John tan p/12345678 e/john123@example.com a/123, jurong Ave 2, #02-25 t/friends t/owesMoney

![Screenshot 2024-11-08 at 5.38.47 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/68fa429b-7e6c-447a-8aab-ff40ff3d532b.png)

expected: Clients with same generic name but different details to be added since they are different people
actual: client not added and duplicate message shown

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: CJianzhi/ped#10

**Comment by mongj** [comment]
@SuhailLoya @AppleJem @celeschai do we want to change the validation logic here?

**Comment by AppleJem** [comment]
Add under future plans for enhanced duplicate client detection to allow this

**Comment by SuhailLoya** [comment]
will be added as planned enhancement
