### ISSUE TITLE
[PE-D][Tester B] Wrong command given in the picture for "add n/David..." in developer's guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#237]
![image.png](https://raw.githubusercontent.com/QinHaichen12/ped/main/files/fbb3698d-8529-4d5d-b1ff-1df5948e0cb2.png)

the command should read "add n/David ..." instead to ensure consistency with the step description.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: QinHaichen12/ped#14

**Comment by AppleJem** [comment]
I don't think this is an issue because that's pseudocode right?

**Comment by AppleJem** [comment]
Will remove the quotation and put a bracket to show that it's pseudocode
