### ISSUE TITLE
[PE-D][Tester B] Loading corrupted data file doesn't show any error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#241]
After putting invalid inputs inside the datafile, loading the app displays an empty page instead of informing the user that the data file is wrong. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: QinHaichen12/ped#16

**Comment by mongj** [comment]
this behavior is inherited from ab3 and also explicitly mentioned in user guide [here](https://ay2425s1-cs2103t-w13-2.github.io/tp/UserGuide.html#editing-the-data-file)

**Comment by SuhailLoya** [comment]
Not important enough to be resolved in v1.6 since users shouldn't change the data file if they are not familiar with it as mentioned in UG
