### ISSUE TITLE
[PE-D][Tester E] adding patient with name too long stalls the application and is unable to create

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#248]
steps to reproduce

1. manually create name that is 83,886,080 characters long
2. try to run the add command
3. application stalls 
![Screenshot 2024-11-08 at 6.47.05 PM.png](https://raw.githubusercontent.com/tohhengxing/ped/main/files/72deaa8f-25f7-46c1-b0ec-8fbd0e98fa75.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tohhengxing/ped#2

**Comment by celeschai** [comment]
Closed by https://github.com/AY2425S1-CS2103T-W13-2/tp/pull/259
