### ISSUE TITLE
[PE-D][Tester A] Email input that meets requirement specified is not accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-2/tp#250]
## email input not accepted even if it does not violate the Email message constraint for local-part

steps to reproduce
1) add n/John Doe p/98765432 e/j++ohnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney

![Screenshot 2024-11-08 at 7.11.37 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/85703f24-3343-4bf1-aa8b-c143d40399a3.png)

expected: email with two consecutive special characters to be valid as it meets the local-part constraint and client to be added
actual: email message constraint displayed

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: CJianzhi/ped#14

**Comment by celeschai** [comment]
Closed by #259
