### ISSUE TITLE
[PE-D][Tester A] addlog command usage message different from expected behaviour

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-2/tp#255]
## Not very sure of what does "Existing values will be overwritten by the input values." mean when using the command

steps to reproduce
1) add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney
2) addlog 1 r/First meetup. d/2019-10-15 14:00
3) addlog 1 r/REAL First meetup. d/2019-10-15 14:00

![Screenshot 2024-11-08 at 8.20.38 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/d7544841-003a-46af-b8a3-e131326d878b.png)

![Screenshot 2024-11-08 at 8.17.28 PM.png](https://raw.githubusercontent.com/CJianzhi/ped/main/files/38e02ba8-ad6b-4658-a42f-775312033218.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: CJianzhi/ped#19

**Comment by mongj** [comment]
@celeschai maybe can take a look at this?
