### ISSUE TITLE
Allow field-level update

### ISSUE THREAD

**Issue by mongj** [AY2425S1-CS2103T-W13-2/tp#52]
**Is your feature request related to a problem? Please describe.**
Currently when a user updates a contact, he/she needs to type in all the information again (including the fields that are not changed). This new person then replaces the old person object.

**Describe the solution you'd like**
We should allow field-level update to any contact, instead of treating every person as immutable objects. If a user only wants to update the name, he/she should be able to specify just the user's id and the new name, and the system will update the name accordingly while keeping the other fields intact.

**Comment by AppleJem** [comment]
This was already present in AB3
