### ISSUE TITLE
Update mention of Address Book to be consistent with CareConnect

### ISSUE THREAD

**Issue by mongj** [AY2425S1-CS2103T-W13-2/tp#56]
Currently, terms like "Address Book", "Address App" etc. are still used in various places across the app (such as in the app title, name of the storage file on disk etc.)

We may want to consider renaming these to better reflect the purpose of our app which is an address book specifically for managing social work cases

**Alternative considered**
Or we can just leave it as it is, since Address Book technically also captures what we're doing

**Comment by AppleJem** [comment]
fixed with commit 7ada1d8671a2d22999b4bc7c93428faf40f98559
