### ISSUE TITLE
Enhancing Find Command Results

### ISSUE THREAD

**Issue by SuhailLoya** [AY2425S1-CS2103T-W13-2/tp#73]
**Is your feature request related to a problem? Please describe.**
#72 will allow partial string searching for each word in the query string for find command. But one possible drawback of this is that too many strings might match. We should probably implement an enhancement to mitigate this.

**Describe the solution you'd like**
1. Possibly enforce a minimum length for the search string so not too many matches are returned
2. Possibly implement some sort of sorting in the filtered list displayed so more closely matching names are shown first

**Comment by celeschai** [comment]
After closing #75 it seems that 2. will be fulfilled when the filtered list is returned in lexicographical order. 
Can I confirm that implementing 1. will suffice in this case?

**Comment by SuhailLoya** [comment]
yep, I think this would suffice considering the number of beneficiaries will not be very large since the target user is a single social worker. Thanks!
