### ISSUE TITLE
Live update of search list with find command

### ISSUE THREAD

**Issue by AppleJem** [AY2425S1-CS2103T-W13-2/tp#82]
Currently, when the find command is used, the user can only see the result after pressing enter.
If they make a mistake, they might only realize upon pressing enter. 

Live updating the list of contacts would solve this problem, with the added benefit of making the interface more response to user input

**Comment by mongj** [comment]
I think it's a good idea! Would it be confusing for the users though? Since now we implicitly have 2 types of commands, one which require the user to press "enter" and one which does not.

**Comment by mongj** [comment]
closing this due to feature freeze
